# fly.toml file generated for ts3flyio on 2022-06-17T11:14:56+08:00

app = "ts3flyio"
kill_signal = "SIGINT"
kill_timeout = 300
processes = []

[env]

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 9987
  processes = ["app"]
  protocol = "udp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 10011

  [[services.ports]]
    port = 30033

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
